### ISSUE TITLE
The __getitem__ does not adapt to E2E

### ISSUE THREAD

**Issue by Harry-Up** [arthurdouillard/incremental_learning.pytorch#11]
Hello,

Thanks for your continual updates. However, in this version,  the __getitem__ of the data loader seems not to adapt to E2E, in which 'real_idxes' and 'idxes' are needed. This information is not provided in this version, while it is ok in old version.

**Comment by arthurdouillard** [comment]
Hello,

My remote code is not up-to-date compard to by local code.

Please see how I did with iCaRL. The new loader doesn't return the indexes as they are not needed anymore. Instead of saving the previous model outputs and matching them with the new model outputs using the indexes, I choose to re-do a forward pass with the old model given the current inputs.

Hope that helps.
