### ISSUE TITLE
A small bug & option file for UCIR model is missing.

### ISSUE THREAD

**Issue by suanrong** [arthurdouillard/incremental_learning.pytorch#20]
Nice work!

A small bug I found:
In your models/ucir.py:105 ,  test_loader should be data_loader.

I want to run experiments on ucir model.  Cound you please provide an option file about ucir model? 

Thanks~

**Comment by arthurdouillard** [comment]
Hello,

Thanks for catching this mistake, I've fixed it.

I've just pushed an option file for UCIR (https://github.com/arthurdouillard/incremental_learning.pytorch/blob/master/options/ucir/ucir_cifar100.yaml). You should use it with a data option files (see options/data).

Last time I've checked (several months ago) my UCIR was a bit worse (~2pts) than the paper UCIR, mainly because of the regularization loss. That is why in our paper PODNet, we used instead the original UCIR code base (https://github.com/hshustc/CVPR19_Incremental_Learning).

**Comment by suanrong** [comment]
Thanks for you nicely reply~
