### ISSUE TITLE
About UCIR on CIFAR100

### ISSUE THREAD

**Issue by QWERZPY** [arthurdouillard/incremental_learning.pytorch#44]
Thank you so much for your great work!

Recently, I attempted to reproduce UCIR model on CIFAR100. And I found the first run was perfectly fine, however, the performance dropped dramatically in the second and third run. After calculating the average points, the results are poor.

Here is the log:
> 2021-08-17:08:02:07 [train.py]: Results done on 3 seeds: avg: 43.24 +/- 7.77, last: 33.6 +/- 9.01, forgetting: 30.87 +/- 6.26
2021-08-17:08:02:07 [train.py]: Individual results avg: [49.33, 45.9, 34.49]
2021-08-17:08:02:07 [train.py]: Individual results last: [40.5, 36.9, 23.4]
2021-08-17:08:02:07 [train.py]: Individual results forget: [29.35, 25.51, 37.75]

Thanks for your time and consideration, and best wishes.

**Comment by arthurdouillard** [comment]
Hey,

Just so you know, the performance of my version of UCIR are not SotA, I've always been a few points behind the official code (that you can find on github).

Although, it's indeed weird that the first run seems ok but not the latter ones.

- what is the setting 50-10? 50-1? 
- have you try to run independently each of the runs to see if there isn't a unwanted relation across runs?

**Comment by Kingofolk** [comment]
Hello!
I have met the same problem. My setting is 50-10,160epoch. The results are [64.12, 60.82, 54.92], which is farly lower than reported in the paper of UCIR and in your paper. I have no idea why.
thanks!

**Comment by arthurdouillard** [comment]
My version of UCIR is not perfect. If you find a way to improve it, please tell me.

But beware that the "UCIR" results in my paper were get from the official code.

**Comment by EvelynChee** [comment]
@arthurdouillard I realise the drop of performance in the 2nd and 3rd run is due to the change in `train_transforms` within the `iCIFAR100` dataset. 

https://github.com/arthurdouillard/incremental_learning.pytorch/blob/0d25c2e12bde4a4a25f81d5e316751c90e6f789b/inclearn/lib/data/datasets.py#L27-L57 

In particular, when `color_jitter` argument is not set, `set_custom_transforms` would pop the `ColorJitter` from `train_transforms`. However, the modified list persists even though the `iCIFAR100` dataset is re-initialised at each run, that is, `RandomHorizontalFlip` and `RandomCrop`  would be popped out in the 2nd and 3rd run respectively. The issue no longer occurs after I change Line 42 to `self.train_transforms = self.train_transforms[:-1]` and  and the results seems to be more consistent across runs. Hope this helps.
